import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`, never hand-edited.
    "features/database/generated/**",
  ]),
  // The project's own rules, the ones a machine can actually check.
  // Everything else lives in docs/coding-standards.md as judgment.
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.mts"],
    extends: [tseslint.configs.base],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/prefer-readonly": "error",
      // Type-aware, and the reason the project service is on: a dropped
      // promise in the streaming path fails silently.
      "@typescript-eslint/no-floating-promises": "error",
    },
  },
  // Last, so formatting is Prettier's job and ESLint never argues about it.
  prettier,
]);

export default eslintConfig;
